function t226_floating_init(el){console.log('floating_init');var wnd=$(window);var col=el.parent();el.css('max-width',el.width());el.css('width','100%');col.css('min-height',el.height());var timer;var timer_count=0;var timer_react=5;wnd.scroll(function(){if(timer){window.clearTimeout(timer);if(timer_count>=timer_react){t226_floating_scroll(el,wnd,col);timer_count=0}
timer_count++}
timer=window.setTimeout(function(){t226_floating_scroll(el,wnd,col);timer_count=0},50)});wnd.resize(function(){wnd.scroll()});wnd.scroll()}
function t226_floating_scroll(el,wnd,col){var wnd_height=wnd.height();var wnd_width=wnd.width();if(wnd_width<=1024){el.removeClass('t226__fixedTop');el.removeClass('t226__fixedBottom');el.removeClass('t226__floating');return('')}
el.css('max-width',col.width());if(col.height()<el.height()&&col.height()>0){col.height(el.height())}
var el_height=el.height();var col_top=col.offset().top;var col_width=col.width();var col_height=col.height();var col_bottom=col_top+col_height;var wnd_top=wnd.scrollTop();var wnd_bottom=wnd_top+wnd_height;if(wnd_top+el_height+50>=col_bottom){el.addClass('t226__fixedBottom');el.removeClass('t226__fixedTop');el.removeClass('t226__floating')}else if(wnd_top+50>col_top){el.addClass('t226__floating');el.removeClass('t226__fixedBottom');el.removeClass('t226__fixedTop')}else{el.addClass('t226__fixedTop');el.removeClass('t226__fixedBottom');el.removeClass('t226__floating')}}
function t281_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t281_showPopup(recid);t281_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}}
function t281_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t281_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t281_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t281__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t281_lockScroll()},500)}
el.find('.t-popup').click(function(e){if(e.target==this){t281_closePopup()}});el.find('.t-popup__close').click(function(e){t281_closePopup()});el.find('a[href*=#]').click(function(e){var url=$(this).attr('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t281_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t281_closePopup()}})}
function t281_closePopup(){$('body').removeClass('t-body_popupshowed t281__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t281_unlockScroll()}
$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t281_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t281_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t433_setMapHeight(recid){var el=$('#rec'+recid);var map=el.find('.t433__map');var textwrapper=el.find('.t433__col_text').height();map.css('height',textwrapper);el.find('.t-map').css('height',textwrapper).trigger('sizechange')}
function t466_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t466__item a[href='"+url+"']").addClass("t-active");$(".t466__item a[href='"+url+"/']").addClass("t-active");$(".t466__item a[href='"+pathname+"']").addClass("t-active");$(".t466__item a[href='/"+pathname+"']").addClass("t-active");$(".t466__item a[href='"+pathname+"/']").addClass("t-active");$(".t466__item a[href='/"+pathname+"/']").addClass("t-active")}
function t466_checkAnchorLinks(recid){if($(window).width()>=960){var t466_navLinks=$("#rec"+recid+" .t466__menu a:not(.tooltipstered)[href*='#']");if(t466_navLinks.length>0){t466_catchScroll(t466_navLinks)}}}
function t466_catchScroll(t466_navLinks){var t466_clickedSectionId=null,t466_sections=new Array(),t466_sectionIdTonavigationLink={},t466_interval=100,t466_lastCall,t466_timeoutId,t466_offsetTop=$(".t466").attr("data-offset-top");if(typeof t466_offsetTop=="undefined"){t466_offsetTop=0}
t466_navLinks=$(t466_navLinks.get().reverse());t466_navLinks.each(function(){var t466_cursection=t466_getSectionByHref($(this));if(typeof t466_cursection.attr("id")!="undefined"){t466_sections.push(t466_cursection)}
t466_sectionIdTonavigationLink[t466_cursection.attr("id")]=$(this)});t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop);t466_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t466_navLinks.removeClass('t-active');t466_sectionIdTonavigationLink[t466_getSectionByHref($(this)).attr("id")].addClass('t-active');t466_clickedSectionId=t466_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t466_now=new Date().getTime();if(t466_lastCall&&t466_now<(t466_lastCall+t466_interval)){clearTimeout(t466_timeoutId);t466_timeoutId=setTimeout(function(){t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)},t466_interval-(t466_now-t466_lastCall))}else{t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)}})}
function t466_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,offsetTop){var t466_scrollPosition=$(window).scrollTop(),t466_valueToReturn=t466_clickedSectionId;$(t466_sections).each(function(e){var t466_curSection=$(this),t466_sectionTop=t466_curSection.offset().top,t466_id=t466_curSection.attr('id'),t466_navLink=t466_sectionIdTonavigationLink[t466_id];if(t466_scrollPosition>=(t466_sectionTop-offsetTop)||(t466_sections[0].attr("id")==t466_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t466_clickedSectionId==null&&!t466_navLink.hasClass('t-active')){t466_navLinks.removeClass('t-active');t466_navLink.addClass('t-active');t466_valueToReturn=null}else{if(t466_clickedSectionId!=null&&t466_id==t466_clickedSectionId){t466_valueToReturn=null}}
return!1}});return t466_valueToReturn}
function t466_initMobileMenu(recid){var window_width=$(window).width();var el=$("#rec"+recid);if(980>window_width){el.find(".t466").each(function(){$(this).find(".t466__mobile").css("top",$(this).find(".t466__container__bg_main").innerHeight()+2);$(this).find(".t466__burger, a[href*=#]").click(function(){if($(this).is(".tooltipstered, .t794__tm-link")){return}
$("body").toggleClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideToggle(300)})})}
$('.t466').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideUp(300)})}
function t466_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t466__beforeready')){el.removeClass('t466__beforeready')}}else{el.addClass('t466__beforeready')}}})}
function t466_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t531_setHeight(recid){var t531__el=$("#rec"+recid),t531__image=t531__el.find(".t531__blockimg"),t531__width=t531__image.attr("data-image-width"),t531__height=t531__image.attr("data-image-height"),t531__ratio=t531__height/t531__width,t531__padding=t531__ratio*100;$("#rec"+recid+" .t531__blockimg").css("padding-bottom",t531__padding+"%");if($(window).width()>480){var t531__textwr=t531__el.find(".t531__textwrapper");var t531__deskimg=t531__el.find(".t531__imgwrapper");t531__textwr.each(function(){$(this).css("height",t531__deskimg.innerHeight())})}}
function t545_setHeight(recid){var el=$('#rec'+recid);var t545_height=el.find('.t-container').attr("data-height");el.find('.t-container').each(function(){var highestBox=0;$('.t545__col',this).each(function(){if($(this).height()>highestBox){highestBox=$(this).height()}});if(t545_height>highestBox){highestBox=t545_height}
$('.t545__textwrapper',this).css('height',highestBox);$('.t545__blockimg',this).css('height',highestBox)})}
function t608_setHeight(recid){var el=$("#rec"+recid);var image=el.find(".t608__bgimg");image.each(function(){var width=$(this).attr("data-image-width");var height=$(this).attr("data-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$("#rec"+recid),play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$("#rec"+recid),body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t670__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t686_init(recid){setTimeout(function(){t686_setHeight(recid)},500);var t686__doResize;$(window).resize(function(){clearTimeout(t686__doResize);t686__doResize=setTimeout(function(){t686_setHeight(recid)},200)})}
function t686_setHeight(recid){var t686_el=$('#rec'+recid+' .t686'),t686_ratio=t686_el.attr('data-tile-ratio'),t686_ratioHeight=t686_el.find('.t686__col').width()*t686_ratio;t686_el.find('.t686__row').each(function(){var t686_largestHeight=0,t686_currow=$(this);$('.t686__table',this).each(function(){var t686_curCol=$(this),t686_curColHeight=t686_curCol.find(".t686__textwrapper").outerHeight();if($(this).find(".t686__cell").hasClass("t686__button-bottom")){t686_curColHeight+=t686_curCol.find(".t686__button-container").outerHeight()}
if(t686_curColHeight>t686_largestHeight){t686_largestHeight=t686_curColHeight}});if($(window).width()>=960){if(t686_largestHeight>t686_ratioHeight){$('.t686__table',this).css('height',t686_largestHeight)}
else{$('.t686__table',this).css('height',t686_ratioHeight)}
$('.t686__table',this).css('min-height','auto')}else{$('.t686__table',this).css('min-height',t686_ratioHeight);$('.t686__table',this).css('height','')}
if(t686_GetIEVersion()>0){var curRowHeight=$('.t686__table',this).css('height');$('.t686__bg',this).css('height',curRowHeight);$('.t686__overlay',this).css('height',curRowHeight)}})}
function t686_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t770_init(recid){var rec=$('#rec'+recid);var navElem=rec.find('.t770');var isFixed=(navElem.css('position')=='fixed');var redactorMode=navElem.hasClass('t770_redactor-mode');if(!redactorMode){t770_highlight();navElem.removeClass('t770__beforeready');if(isFixed){t770_checkAnchorLinks(recid)}
if(isFixed&&navElem.attr('data-bgopacity-two')){t770_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(isFixed&&navElem.attr('data-appearoffset')){navElem.removeClass('t770__beforeready');t770_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}
if(rec.find('.t770__imglogo').attr('data-img-width')){t770_setLogoPadding(recid)}
if(rec.find('.t770__mobile_burger').length){t770_createMobileMenu(recid)}
t770_setBg(recid);$(window).bind('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){if($(window).width()>980){var t770__menu=$('#rec'+recid+' .t770');var t770__logo=t770__menu.find('.t770__logowrapper');var t770__leftpart=t770__menu.find('.t770__leftwrapper');var t770__rightpart=t770__menu.find('.t770__rightwrapper');t770__leftpart.css("padding-right",t770__logo.width()/2+50);t770__rightpart.css("padding-left",t770__logo.width()/2+50)}}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t770__list_item a[href='"+url+"']").addClass("t-active");$(".t770__list_item a[href='"+url+"/']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t770_checkAnchorLinks(recid){if($(window).width()>=960){var t770_navLinks=$("#rec"+recid+" .t770__desktoplist .t770__list_item a:not(.tooltipstered)[href*='#']");if(t770_navLinks.length>0){t770_catchScroll(t770_navLinks)}}}
function t770_catchScroll(t770_navLinks){var t770_clickedSectionId=null,t770_sections=new Array(),t770_sectionIdTonavigationLink=[],t770_interval=100,t770_lastCall,t770_timeoutId;t770_navLinks=$(t770_navLinks.get().reverse());t770_navLinks.each(function(){var t770_cursection=t770_getSectionByHref($(this));if(typeof t770_cursection.attr("id")!="undefined"){t770_sections.push(t770_cursection)}
t770_sectionIdTonavigationLink[t770_cursection.attr("id")]=$(this)});t770_updateSectionsOffsets(t770_sections);t770_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t770_updateSectionsOffsets(t770_sections)},200));$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(t770_sections)});setInterval(function(){t770_updateSectionsOffsets(t770_sections)},5000);t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId);t770_navLinks.click(function(){var t770_clickedSection=t770_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t770_clickedSection.attr("id")!="undefined"){t770_navLinks.removeClass('t-active');$(this).addClass('t-active');t770_clickedSectionId=t770_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t770_now=new Date().getTime();if(t770_lastCall&&t770_now<(t770_lastCall+t770_interval)){clearTimeout(t770_timeoutId);t770_timeoutId=setTimeout(function(){t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)},t770_interval-(t770_now-t770_lastCall))}else{t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)}})}
function t770_updateSectionsOffsets(sections){$(sections).each(function(){var t770_curSection=$(this);t770_curSection.attr("data-offset-top",t770_curSection.offset().top)})}
function t770_getSectionByHref(curlink){var t770_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t770_curLinkValue[0]=='/'){t770_curLinkValue=t770_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t770_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t770_curLinkValue.substring(1)+"']")}}
function t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId){var t770_scrollPosition=$(window).scrollTop(),t770_valueToReturn=t770_clickedSectionId;if(t770_sections.length!=0&&t770_clickedSectionId==null&&t770_sections[t770_sections.length-1].attr("data-offset-top")>(t770_scrollPosition+300)){t770_navLinks.removeClass('t-active');return null}
$(t770_sections).each(function(e){var t770_curSection=$(this),t770_sectionTop=t770_curSection.attr("data-offset-top"),t770_id=t770_curSection.attr('id'),t770_navLink=t770_sectionIdTonavigationLink[t770_id];if(((t770_scrollPosition+300)>=t770_sectionTop)||(t770_sections[0].attr("id")==t770_id&&t770_scrollPosition>=$(document).height()-$(window).height())){if(t770_clickedSectionId==null&&!t770_navLink.hasClass('t-active')){t770_navLinks.removeClass('t-active');t770_navLink.addClass('t-active');t770_valueToReturn=null}else{if(t770_clickedSectionId!=null&&t770_id==t770_clickedSectionId){t770_valueToReturn=null}}
return!1}});return t770_valueToReturn}
function t770_setPath(){}
function t770_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t770_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t770_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t770_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t770"),burger=el.find(".t770__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t770_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t794_init(recid){var hook=$("#rec"+recid+" .t794").attr("data-tooltip-hook");if(typeof hook=="undefined"||hook==""){return};var hookLinks=$("a[href='"+hook+"']");hookLinks.addClass("t794__tm-link");hookLinks.attr("data-tooltip-menu-id",recid);t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var submenu=$("#rec"+recid+" .t794__tooltip-menu");if(isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
$(window).bind('scroll',t_throttle(function(){if(submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}},300));$(".t794__tooltip-menu a[href*=#]").click(function(){t794_hideSubmenu(submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu')})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var vIndent=$("#rec"+recid+" .t794").attr('data-tooltip-margin');hookLinks.on("click",function(e){if(submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}else{var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)}
e.preventDefault()});$(document).click(function(e){var isInsideSubmenu=($(e.target).hasClass("t794__tooltip-menu")||$(e.target).parents(".t794__tooltip-menu").length>0);var isAnchor=($(e.target).hasClass("t794__tm-link")||$(e.target).parents(".t794__tm-link").length>0);if(isAnchor){var curAnchor;if($(e.target).hasClass("t794__tm-link")){curAnchor=$(e.target)}else{curAnchor=$(e.target).parents(".t794__tm-link")}
if(curAnchor.attr("data-tooltip-menu-id")!=recid&&submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}}
if(!isInsideSubmenu&&!isAnchor&&submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var vIndent=$("#rec"+recid+" .t794").attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on("mouseover",function(){if($(this).hasClass("t794__tooltip-menu")&&!$(this).hasClass("t794__tooltip-menu_show")){return}
clearTimeout(timer);if($(this).hasClass("t794__tooltip-menu")&&submenu.hasClass("t794__tooltip-menu_show")){return}
var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)});hookLinks.add(submenu).on("mouseout",function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)});hookLinks.on("click",function(e){e.preventDefault()})}
function t794_showSubmenu(curAnchor,submenu,vIndent){var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorLeft=curAnchor.offset().left;if(typeof vIndent!="undefined"&&vIndent!=""){vIndent=vIndent.replace("px","")*1;vIndent=vIndent+10}
var posy=curAnchor.offset().top+anchorHeight+vIndent;var posx=anchorLeft;if(posy+submenuHeight>scrollTop+winHeight){posy=Math.max(posy-submenuHeight-anchorHeight-vIndent*2,scrollTop);submenu.removeClass("t794__tooltip-menu_bottom").addClass("t794__tooltip-menu_top")}else{submenu.removeClass("t794__tooltip-menu_top").addClass("t794__tooltip-menu_bottom")}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=10}}else{posx=winWidth-submenuWidth-10}
submenu.css({"display":"block","left":posx,"top":posy});submenu[0].offsetHeight;submenu.addClass("t794__tooltip-menu_show");curAnchor.addClass("t794__tm-link_active")}
function t794_hideSubmenu(submenu){submenu.css({"display":"","left":"","top":""});submenu.removeClass("t794__tooltip-menu_show");$(".t794__tm-link_active").removeClass("t794__tm-link_active")}
function t794_addArrow(recid,hookLinks){var arrow=$("#rec"+recid+" .t794").attr('data-add-arrow');if(typeof arrow=="undefined"||arrow==""){return};hookLinks.each(function(){var arrowHeight=$(this).height();$(this).append("<div class=\"t794__arrow\" style=\"height: "+arrowHeight+"px;\"></div>")})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t794__list_item a[href='"+url+"']").addClass("t-active");$(".t794__list_item a[href='"+url+"/']").addClass("t-active");$(".t794__list_item a[href='"+pathname+"']").addClass("t-active");$(".t794__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t794__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t794__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}
function t802_insta_init(recid,instauser){var projectid=$('#allrecords').attr('data-tilda-project-id');t802_insta_loadflow(recid,projectid,instauser)}
function t802_insta_loadflow(recid,projectid,instauser){if(instauser==''){var url="https://insta.tildacdn.com/fish/0.json"}else{var url="https://insta.tildacdn.com/json/project"+projectid+"_"+instauser+".json"}
$.ajax({type:"GET",url:url,dataType:"json",success:function(data){if(typeof data=='object'){t802_insta_draw(recid,data)}else{console.log('error. insta flow json not object');console.log(data)}},error:function(){console.log('error load instgram flow')},timeout:1000*90})}
function t802_insta_draw(recid,obj){if(typeof obj.photos=='undefined'){return}
$.each(obj.photos,function(index,item){t802_insta_drawItem(recid,obj.username,item)})}
function t802_insta_drawItem(recid,username,item){var emptyEl=$("#rec"+recid).find(".t802__imgwrapper_empty").first();if(emptyEl.length>0){emptyEl.removeClass("t802__imgwrapper_empty");emptyEl.append('<div class="t802__bgimg" style="background-image:url('+item.url+')"></div>');emptyEl.wrap('<a href="'+item.link+'"></a>');var hoverEl=emptyEl.find(".t802__hover-wrapper");if(hoverEl.length>0&&isMobile==!1){var text=t802_insta_cropText(recid,'@'+username+': '+item.text);hoverEl.append('<div class="t802__hover-filter"></div>');hoverEl.append('<div class="t802__text t-text t-descr_xxs">'+text+'</div>')}}}
function t802_insta_cropText(recid,text){var colsInLine=$("#rec"+recid).find("[data-cols-in-line]").attr("data-cols-in-line");if(colsInLine==6){var maxLength=90}else{var maxLength=130}
if(text.length>maxLength){text=text.substring(0,maxLength);text=text.substring(0,Math.min(maxLength,text.lastIndexOf(" ")));text+=' ...'}
return text}